MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #增加命名空间函数，根URL中app_name是多余参数，要删掉
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
]

MyBlog/article/urls.py
from . import views, list_views
from django.conf.urls import url

app_name = 'article'  # 在子URL中加上这一行

urlpatterns = [
    url(r'^article_column/$', views.article_column, name="article_column"),

    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),

    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),

    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^del-article/$', views.del_article, name="del_article"),

    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

MyBlog/blog/urls.py
from . import views
from django.conf.urls import url

app_name = 'blog'   #在子URL中加上这一行
urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

MyBlog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
# from django.core.urlresolvers import reverse

class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column

# 文章标签的模型类
class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name="tag", on_delete=models.CASCADE)
    tag = models.CharField(max_length=500)

    def __str__(self):
        return self.tag

class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)

    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)#根据ID和slug建立索引

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])

# 文章评论模型类
class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments", on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

MyBlog/article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment, ArticleTag

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = ArticleTag
        fields = ('tag', )

MyBlog/article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse
#内置分页功能
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import ArticleColumn, ArticlePost, ArticleTag
from .forms import ArticleColumnForm, ArticlePostForm, ArticleTagForm
import json


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")

# 修改栏目名
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")

# 删除栏目
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()

                tags = request.POST['tags']
                if tags:
                    for atag in json.loads(tags):
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)

                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()

        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns, "article_tags":article_tags})

# 文章列表显示（增加了分页）
@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    # 每页6条数据
    paginator = Paginator(articles_list, 3)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})

# 查看文章详情——检查登录状态
@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})

# 查看文章详情——不检查登录状态
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})

# 删除文章
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")

# 修改文章
@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html", {"article": article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

# 文章标签
@login_required(login_url='/account/login')
@csrf_exempt
def article_tag(request):
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author=request.user)
        article_tag_form = ArticleTagForm()
        return render(request, "article/tag/tag_list.html", {"article_tags": article_tags, "article_tag_form": article_tag_form})

    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("the data cannot be save.")
        else:
            return HttpResponse("sorry, the form is not valid.")

# 删除文章标签
@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")

MyBlog/templates/article/list/article_detail.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    {% with total_likes=article.users_like.count users_like=article.users_like.all %}

        <div class="container">
            <div class="col-md-9">
                <header>
                    <h1>{{ article.title }}</h1>
                    <p>
                        <a href="{% url 'article:author_articles' article.author.username %}">
                            {{ article.author.username }}
                        </a>
                        <span style="margin-left:20px"
                              class="glyphicon glyphicon-thumbs-up">有{{ total_likes }}人赞过</span>
                        <span style="margin-left:20px">有 {{ total_views }} 人看过</span>
                    </p>
                    <p><span
                            style="margin-right: 10px"><strong>本文标签:</strong></span> {{ article.article_tag.all | join:", " }}
                    </p>
                </header>

                <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
                <div id='editormd-view'>
                    {{ article.body | markdown }}
                </div>
                <div>
                    <p class="text-center">
                        <a onclick="like_article({{ article.id }}, 'like')" href="#"><span
                                class="glyphicon glyphicon-thumbs-up">怒赞一下</span></a>
                        <a onclick="like_article({{ article.id }}, 'unlike')" href="#"><span style="margin-left: 15px;"
                                                                                             class="glyphicon glyphicon-thumbs-down">不睬他</span></a>
                    </p>
                </div>
                <div>
                    <p class="text-center"><strong>点赞本文的读者</strong></p>
                    {% for user in article.users_like.all %}
                        <p class="text-center">{{ user.username }}</p>
                    {% empty %}
                        <p class="text-center">还没有人对此文章表态</p>
                    {% endfor %}
                </div>
                <hr>
                <div>
                    <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有{{ comments.count }}条评论</h3>
                    {% for comment in article.comments.all %}
                        <div>
                            <p><strong>{{ comment.commentator }}</strong>说：</p>
                            <p style="margin-left:40px;">{{ comment.body }}</p>
                        </div>
                    {% empty %}
                        <p>暂无评论，快来抢沙发！</p>
                    {% endfor %}

                    <h3><span class="glyphicon glyphicon-send"></span>看文章，发评论，不要沉默</h3>
                    <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                            <div class="col-sm-10">
                                {{ comment_form.commentator }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                            <div class="col-sm-10">
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-3">
                <p class="text-center"><h3>最受欢迎文章</h3></p>
                <div>
                    <ul>
                        {% for article_rank in most_viewed %}
                            <li>
                                <a href="{{ article_rank.get_url_path }}">{{ article_rank.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <hr>
                <p class="text-center"><h3>最新文章</h3></p>
                        <div>{% latest_articles 6 %}</div>
                <hr>
                <p class="text-center"><h3>最多评论文章</h3></p>
                    {% most_commented_articles as most_comments %}
                <div>
                    <ul>
                        {% for comment_article in most_comments %}
                            <li>
                                <a href="{{ comment_article.get_url_path }}">{{ comment_article.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <hr>
                <p class="text-center">
                <h3>相似文章推荐</h3></p>
                <div>
                    <ul>
                        {% for similar in similar_articles %}
                            <li>
                                <a href="{{ similar.get_url_path }}">{{ similar.title }}</a>
                            </li>
                        {% empty %}
                            <p>抱歉！暂时没有相似文章</p>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
        <script src='{% static "js/jquery.js" %}'></script>
        <script src='{% static "editor/lib/marked.min.js" %}'></script>
        <script src='{% static "editor/lib/prettify.min.js" %}'></script>
        <script src='{% static "editor/lib/raphael.min.js" %}'></script>
        <script src='{% static "editor/lib/underscore.min.js" %}'></script>
        <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
        <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
        <script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
        <script src='{% static "editor/editormd.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script type="text/javascript">
            $(function () {
                editormd.markdownToHTML("editormd-view", {
                    htmlDecode: "style,script,iframe",  // you can filter tags decode
                    emoji: true,
                    taskList: true,
                    tex: true,  // 默认不解析
                    flowChart: true,  // 默认不解析
                    sequenceDiagram: true,  // 默认不解析
                });
            });

            function like_article(id, action) {
                $.ajax({
                    url: "{% url 'article:like_article' %}",
                    type: "POST",
                    data: {"id": id, "action": action},
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("感谢点赞");
                            window.location.reload();
                        } else {
                            layer.msg("我会继续努力");
                            window.location.reload();
                        }
                    },
                });
            }
        </script>
    {% endwith %}
{% endblock %}

MyBlog/templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} 全部文章 {% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h2>阅读，丰富头脑，善化行为</h2>
    <p>这里已经有{% total_articles %}篇文章供你阅读！</p>
</div>
<div class="container">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <p class="list-group-item-text">概要：{{article.body|slice:'70'| linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
{% endblock %}

MyBlog/templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}该作者的所有文章{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读，丰富头脑，善化行为</h1>
</div>
<div class="container">
<div class="col-md-8">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active"><h4 class="list-group-item-heading">{{article.title}}</h4></a>
      	<p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
       	<p class="list-group-item-text">概要：{{article.body|slice:'70'|linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
<div class="col-md-4">
<div>
    {% if userdata.photo %}
    <img src="{{ userdata.photo | striptags }}" class="img-circle" id="my_photo" name="user_face">
    {% else %}
    <img name="user_face" src="{% static 'images/touxiang1.jpg' %}" class="img-circle" id="my_photo">
    {% endif %}
</div>
<div>
    <p>{{ user.username }} 共发表文章{% author_total_articles user %}篇！</p>
    {% if userdata %}
    <p>{{ userdata.company }}
    <p>{{ userdata.aboutme }}</p>
{% else %}
<p>这个作者太懒了，什么也没有留下。</p>
{% endif %}
</div>
</div>
</div>
{% endblock %}

MyBlog/templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
    	<a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>