MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #增加命名空间函数，根URL中app_name是多余参数，要删掉
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^home/', TemplateView.as_view(template_name="home.html"), name="home"),
]

MyBlog/account/urls.py
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'account'  # 在子URL中加上这一行

urlpatterns = [
    # url(r'^login/$', views.user_login, name="user_login"),  #自定义的用户登录
    url(r'^login/$', auth_views.LoginView.as_view(template_name='account/login.html'), name="user_login"),  # django内置登录
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='account/logout.html'), name="user_logout"),
    url(r'^register/$', views.register, name="user_register"),

    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(
            template_name='account/password_change_form.html',
            success_url=reverse_lazy('account:password_change_done')
        ),
        name='password_change'),
    url(r'^password-change-done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='account/password_change_done.html'
        ),
        name="password_change_done"),

    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='account/password_reset_form.html',
            email_template_name='account/password_reset_email.html',
            subject_template_name='account/password_reset_subject.txt',
            success_url=reverse_lazy('account:password_reset_done')
        ),
        name='password_reset'),

    url(r'^password-reset-done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password_reset_done.html'
        ),
        name="password_reset_done"),

    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password_reset_confirm.html',
            success_url=reverse_lazy('account:password_reset_complete')
        ),
        name='password_reset_confirm'),

    url(r'^password-reset-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html',
        ),
        name='password_reset_complete'),

    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
    url(r'^my-image/$', views.my_image, name="my_image"),
]

MyBlog/article/urls.py
from . import views, list_views
from django.conf.urls import url

app_name = 'article'  # 在子URL中加上这一行

urlpatterns = [
    url(r'^article_column/$', views.article_column, name="article_column"),

    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),

    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),

    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^del-article/$', views.del_article, name="del_article"),

    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
    url(r'^article-tag/$', views.article_tag, name="article_tag"),
    url(r'^del-article-tag/$', views.del_article_tag, name="del_article_tag"),
]

MyBlog/blog/urls.py
from . import views
from django.conf.urls import url

app_name = 'blog'   #在子URL中加上这一行
urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

MyBlog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-sidth, initial-scale=1"/>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}{% endblock %}
    </body>
</html>

MyBlog/templates/footer.html
<div class="container">
    <hr/>
    <p class="text-center">copy right@唯唯俱乐部</p>
</div>

MyBlog/templates/header.html
{% load staticfiles %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">
                <img src="{% static '/images/ying.jpg' %}" width="100px"/>
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav navbar-left" role="navigation">
                <li><a href="{% url 'home' %}">首页</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'blog:blog_title' %}">博客</a></li>
                {% endif %}

                <li><a href="{% url 'article:article_titles' %}" >文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                    <li>
                        <div class="dropdown" style="margin-top:8px">
                            <button class="btn btn-default dropdown-toggle" type="button" id='dropdownMenu'
                                    data-toggle="dropdown">
                                {{ user.username }}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人资料</a></li>
                                <li><a href="{% url 'article:article_column' %}">栏目管理</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'account:user_logout' %}">退出登录</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">登录</a></li>
                    <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
</div>

MyBlog/templates/home.html
{% extends "base.html" %}
{% block title %}唯唯博客首页{% endblock %}
{% block content %}
<div class="text-center">
    <h3>欢迎来到唯唯博客！</h3>
    <h5>不是因为有希望才坚持，而是因为坚持才有希望。</h5>
    {% load staticfiles %}
    <img src="{% static 'images/homepage.jpg' %}">
</div>
{% endblock %}

MyBlog/templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}    
    <a href="?page={{ page.previous_page_number }}">上一页 | </a>
    {% endif %}
    <span class="current">
      第 {{ page.number }} / {{ page.paginator.num_pages }} 页
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}"> | 下一页</a>
    {% endif %}
  </span>
</div>